### ISSUE TITLE
diagram is only shown for milliseconds when visited the site via https://matrix.org/#diagram

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/matrix.org#1390] opened 2022-07-25 16:36 UTC
**Describe the bug**
Firefox:
When you join matrix via this link, the diagram is only shown like a millisecond
https://matrix.org/#diagram

Chromium:
When you join matrix via this link and then reload the page, the diagram is only shown like a millisecond
https://matrix.org/#diagram

**Expected behavior**
diagram is shown like when you join the side via https://matrix.org and then scroll down

**Screenshots**
![grafik](https://user-images.githubusercontent.com/30293477/180829128-08023e2b-4736-4b69-ad28-858d3f090b3a.png)

Desktop
 - OS:  Ubuntu Mate 22.04
 - Browser chromium/firefox
 - Version 103.0.5060.114  / 102.0.1 (64-Bit)

**Comment by MadLittleMods** [comment] 2022-07-25 17:03
I'm unable to reproduce and nothing has changed in this area of the site.

**Comment by JokerGermany** [comment] 2022-07-26 11:55
https://youtu.be/V8pBbOptGdQ

When it's flickering i am pressing F5

**Comment by MadLittleMods** [comment] 2022-07-26 17:05
Ahh, thanks for the video @JokerGermany 👍

Your report clearly spells out to visit https://matrix.org/#diagram specifically which links directly to the diagram and I can reproduce after several tries. It even happens with https://matrix.org/ but both are flakey scenarios and doesn't happen every time.

There are several errors on the page normally and I can't spot the difference between when it decides to work or not.

**Comment by AshishPandagre** [comment] 2023-02-09 13:35
https://user-images.githubusercontent.com/53047854/217824976-dd5338cc-0659-48f7-ad6e-018e93cebaa8.mp4

I noticed that this diagram flickers only when I refresh the page.
The diagram is fully loaded if I click on the url tab and then press enter (as shown in video).

Most weird thing I have ever seen !!!

**Comment by thibaultamartin** [comment] 2023-06-22 15:01
Closing as duplicate of #527

**Closed by thibaultamartin** 2023-06-22 15:01 UTC
Labels: bug, help wanted
