### ISSUE TITLE
Server Setup guide links are wrong

### ISSUE THREAD

**Issue by JMS55** [matrix-org/matrix.org#1252] opened 2022-02-03 16:29 UTC
In the matrix "Guides for Developers", the two links under "Server Setup" are wrong, and point to the js-sdk and the client-server spec instead of anything to do with installing synapse.

https://matrix.org/docs/develop/

**Comment by MadLittleMods** [comment] 2022-02-03 16:38
Duplicate of https://github.com/matrix-org/matrix.org/issues/965

**Closed by MadLittleMods** 2022-02-03 16:38 UTC
Labels: bug
