### ISSUE TITLE
"website" links in twim headers are missing any indication of being links

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix.org#1756] opened 2023-04-29 12:36 UTC
# [zola]

![image](https://user-images.githubusercontent.com/2803622/235302824-59204f8f-1071-49bd-bcd2-7bd1dc7a4d3d.png)
 just looks like regular text

**Comment by thibaultamartin** [comment] 2023-04-30 11:41
Duplicate of #1529

**Closed by thibaultamartin** 2023-04-30 11:41 UTC
Labels: zola
