### ISSUE TITLE
Text not centered in the stability labels next to bridges

### ISSUE THREAD

**Issue by robintown** [matrix-org/matrix.org#1742] opened 2023-04-28 14:16 UTC
For example the 'beta' label here:

![Screenshot 2023-04-28 at 10-12-39 Matrix org - Discord](https://user-images.githubusercontent.com/48614497/235171654-060caffa-61cf-4106-beec-06712f080e85.png)

**Comment by thibaultamartin** [comment] 2023-04-28 14:17
Closing as duplicate of #1719, but thanks for the bug hunt!

**Closed by thibaultamartin** 2023-04-28 14:17 UTC
