### ISSUE TITLE
shop.matrix.org sticker collection still includes Riot.im stickers, instead of Element

### ISSUE THREAD

**Issue by tim-seoss** [matrix-org/matrix.org#823] opened 2020-09-02 12:09 UTC
The stickers at https://shop.matrix.org/product/sticker-collection-15-stickers-in-3-designs include the old Riot.im brand, instead of Element.

**Comment by moritzdietz** [comment] 2020-09-07 18:38
I'd love to see new Stickers too! So folks you gotta get these limited edition retro "Riot" Stickers fast before they are gone ;-)

**Comment by afranke** [comment] 2021-07-26 05:19
Oh no! Looks like they are indeed gone now! :-)

**Comment by MadLittleMods** [comment] 2021-08-18 01:00
Going to close this as the Riot.im stickers aren't in the pack anymore.

I think the hold-up on Element merch is the specific green color which is supposedly hard to reproduce properly.

**Closed by MadLittleMods** 2021-08-18 01:00 UTC
