### ISSUE TITLE
Two .woff2 files from the Bitter font get inlined in base64

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix.org#705] opened 2020-04-23 15:51 UTC
Looking at view-source:https://matrix.org/ one can see that two font files got inlined.

https://github.com/KyleAMathews/typefaces/blob/8c418fe2dca2d5c11f50a0a2c1861ad759b24989/packages/bitter/index.css#L23
and
https://github.com/KyleAMathews/typefaces/blob/8c418fe2dca2d5c11f50a0a2c1861ad759b24989/packages/bitter/index.css#L36

I'm not sure what makes these different as other fonts from the same import are externally linked.

**Comment by MadLittleMods** [comment] 2021-08-17 22:00
Duplicate of https://github.com/matrix-org/matrix.org/issues/409

**Closed by MadLittleMods** 2021-08-17 22:00 UTC
