### ISSUE TITLE
Add matrix-appservice-bridge to the SDK page

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix.org#935] opened 2021-01-21 19:00 UTC
Add [`matrix-appservice-bridge`](https://github.com/matrix-org/matrix-appservice-bridge) to the SDK page, https://matrix.org/sdks/

**Comment by afranke** [comment] 2021-07-26 05:20
Duplicate of #862?

**Comment by MadLittleMods** [comment] 2021-07-26 20:37
Good find @afranke, I've created https://github.com/matrix-org/matrix.org/pull/1030 to fix the issue overall 👍

**Closed** 2021-07-30 02:17 UTC
