### ISSUE TITLE
Add a Dashboard that shows the state of Matrix

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#745] opened 2020-05-26 09:38 UTC
Does such a unified dashboard exist already?

I'd like to see:
- Number of Homeservers
- Homeservers ranked by health (ping, availability...)
- Number of Globally visible accounts
- Number of messages sent per day
- Estimated energy and CO2 footprint of the Matrix ecosystem per day
- New Tweets and Toots about matrix

Any additional ideas?

**Comment by thibaultamartin** [comment] 2023-06-22 09:16
We can only do this as seen from the matrix.org homeserver. Closing as a duplicate of #67 :)

**Closed by thibaultamartin** 2023-06-22 09:16 UTC
Labels: enhancement
