### ISSUE TITLE
Try Matrix Now grid is hard to read—Images feel disconnected from the rest of the section.

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1218] opened 2022-01-05 01:45 UTC
On https://matrix.org/docs/projects/try-matrix-now there are plenty of text and their screenshots. However, due to the lack of a background, borders shadows or anything it is pretty hard to connect which images go to which title. 

Something like a light grey background per "card"/section or shadows to make them like cards may help. 

Basically this is what I have in mind:

![image](https://user-images.githubusercontent.com/1374914/148147514-9ffdafeb-3a71-4598-8072-10925413baa1.png)

**Comment by afranke** [comment] 2022-01-05 08:00
Duplicate of #925

**Closed by afranke** 2022-01-05 08:00 UTC
