### ISSUE TITLE
Link to "members of the Core Team" on proposals page is dead

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix.org#310] opened 2019-01-04 15:54 UTC
[The proposals page](https://matrix.org/docs/spec/proposals) links to https://github.com/orgs/matrix-org/teams/spec-core-team/members as defining the current core team members. At least to me as someone not in the matrix-org organization, that link is dead (I get github's generic 404 page not found).

**Comment by jryans** [comment] 2019-01-04 15:56
Thanks for the report! This is a duplicate of #283.

**Closed by jryans** 2019-01-04 15:56 UTC

**Comment by non-Jedi** [comment] 2019-01-04 15:59
Ah. Sorry about the dupe then
