### ISSUE TITLE
Add "Previous" button alongside "Next" button is the index Matrix description slideshow

### ISSUE THREAD

**Issue by joeitu** [matrix-org/matrix.org#1240] opened 2022-01-27 13:31 UTC
Hello, 

On the index page, there is a slideshow describing how matrices work. Unfortunately it only has a "Next" button and the only way to go back a slide is to refresh the page. Would be convenient to have a "Previous" button too.

**Comment by clesiaroberto** [comment] 2022-04-14 18:25
Hello! Could you please share the link to this issue

**Comment by MadLittleMods** [comment] 2022-04-14 18:27
@clesiaroberto The *How does it work?* section on https://matrix.org/

![](https://user-images.githubusercontent.com/558581/163453810-01fc7cfb-fd14-4906-a49e-2be597abe565.png)

**Comment by aaronraimist** [comment] 2022-06-12 19:20
Duplicate of https://github.com/matrix-org/matrix.org/issues/16

**Closed** 2022-06-13 09:57 UTC
Labels: enhancement
