### ISSUE TITLE
Global outage on matrix.org

### ISSUE THREAD

**Issue by shmerl** [matrix-org/matrix.org#1601] opened 2023-01-06 03:07 UTC
Looks like Matrix service on matrix.org is down as of January 6, 2023, 3:05 UTC (Element can't connect to it).

Despite here saying "no incidents": https://status.matrix.org

**Comment by lost-rob0t** [comment] 2023-01-06 03:39
Is this related?

![screen13](https://user-images.githubusercontent.com/104283403/210925294-e7b22e5a-7412-4800-8100-6ac29ba2e8cb.png)

**Comment by shmerl** [comment] 2023-01-06 03:40
I noticed that too. Possible.

**Comment by austinbutler** [comment] 2023-01-06 03:42
Yeah that's likely the cause.

**Comment by TheEternalSanguin123** [comment] 2023-01-06 03:57
I hope these are easy to fix problems, i was talking to a friend when all of a sudden everything jsut stopped working after i restarted cause some images weren't sending. I do hope the problem gets acknowledged at the very least, having to make an entirely new server or join one would be hard with how many messages i have.

**Comment by shmerl** [comment] 2023-01-06 03:59
Not sure what matrix.org support is, but people might be sleeping. Hopefully admins can fix it quickly when they realize there is an issue.

**Comment by TheEternalSanguin123** [comment] 2023-01-06 04:04
Hopefully it would suck if everything stopped working till the next day or something....

**Comment by turt2live** [comment] 2023-01-06 04:21
Hi all, just confirming that there is an operational issue on matrix.org at the moment. The operations team was notified shortly after the incident began and is currently working on remediation.

As far as we can tell, the problem is not as simple as fixing an SSL certificate. We'll post more information here as we have it.

Thanks for your patience.

**Comment by TheEternalSanguin123** [comment] 2023-01-06 04:29
Thank you for updating us sir, and we'll be as patient as needed as long as things can be fixed

**Comment by Spl0itable** [comment] 2023-01-06 04:32
Appears to be coming back online now. Cheers for the quick fix. Although, this reminded me I planned to migrate to different homeserver 😅

**Comment by turt2live** [comment] 2023-01-06 04:34
Connectivity will be intermittent - the issue has not been resolved as of yet.

We're working on updating status.matrix.org as well, but have prioritized fixing the service. The checks aren't picking up this failure mode for some reason, and we'll be sure to review what's going wrong with the status page as part of our incident retrospective internally.

**Comment by TheEternalSanguin123** [comment] 2023-01-06 04:35
k that explains

**Comment by TheEternalSanguin123** [comment] 2023-01-06 05:12
Thank you all for your hard work on fixing and noticing this, even if its not fixed tonight hopefully by morning i can get back to some time with my friends. Wish you the best on fixing the issues and a good rest of your day-night.

**Comment by dreaddr** [comment] 2023-01-06 05:42
Seems other homeservers work just fine. Only matrix.org is affected but well, thats a huge majority of the people/rooms I want to chat with unfortunately.

**Comment by turt2live** [comment] 2023-01-06 05:53
This incident should now be resolved, and matrix.org is catching up on traffic. 

Thanks all for your patience and reports - we've learned quite a bit about the particular failure mode, and are already prepared for next time (hopefully there isn't a next time).

**Comment by unknown-user-9246102101** [comment] 2023-01-06 05:56
Thank you. You guys are so quick to resolve any issues I have had. I appreciate it.

**Comment by turt2live** [comment] 2023-01-06 06:01
Internally, the incident has formally been resolved - closing the issue.

Thanks again for the reports.

**Closed by turt2live** 2023-01-06 06:01 UTC
