### ISSUE TITLE
link to hello-matrix.net's server list as loudly as possible

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#95] opened 2018-02-28 23:21 UTC

**Comment by turt2live** [comment] 2018-02-28 23:39
This sounds like a duplicate of https://github.com/matrix-org/matrix-doc/issues/765 (which should probably be migrated here anyways)

**Comment by turt2live** [comment] 2018-02-28 23:39
Related: https://github.com/matrix-org/matrix.org/issues/28

**Comment by MTRNord** [comment] 2018-03-01 10:42
Even the following more fits riot I mention it here: (if wanted I make it a issue at riot) 

As Hello-matrix has a api it might make sense to add a dropdown list on the register and login Page containing the "free to join" Servers. With the idea that people click one other than matrix.org. (I currently are implementing it in my client Morpheus.)

Also somehow show in the ping from The users location to the Server and the number of registered users might make sense when doing it

**Comment by pierreozoux** [comment] 2018-03-04 21:18
Ok, this is really interesting you are discussing this right now.
This problem is a known problem:
 1. How to list service provider
 2. How to help end user pick among a list of hosting provider

Currently every free software is solving this with a different solution and we think that it is not efficient for us, service provider and for software developers to reinvent the wheel each time.

We think that using linked data could be a solution to sdandardize the information you need to know about a hoster.

In the case of a multitenant app like matrix or riot, I think it would make sense to have this data in the app itself and registered in an admin interface (or some config file).

In the solution space, I'd say that we have to work on the following:
 - identify info we need about a hoster
 - identify if schema.org is enough
 - if not PR schema.org to add specific fields about the specific from free software hoster
 - add a way for the hoster to specify this fields in riot web app
 - make these fields available in a json-ld on the landing page

Then as a hoster, if I want to be listed on the official list, it would be a matter for me to just PR and add the URL of my instance. 

Then there is still the need to list these hosters ( I'd say curate, some people will want free, other libre, other paid services..).

Then we need to create a tool to parse these json-ld and create a list from these metadata. But this is rather trivial.

We'll also need to figure out, one day, how to add "decorators" to this list, like uptime, TLS quality, TOS;dr, exclusively free software, and so on.

Also, how to help people choose there instance hoster (I'm a company, and I want matrix.organization.org where do I go?).

And still, we need to figure out a way to help the end user choose an instance.
Nextcloud present them randomly on there page, and the plan for the mobile app is to let the end user choose among a list of 3 providers (chooses with language, timezone, TLS quality, uptime).

We can also take a look at how Mastodon does, it is pretty advanced compare to the rest of FreeSoftware. Nextcloud is also quite nice!

Sorry for the long text, but the topic is hot for us, and we think about creating a project around this specific topic, so I thought I'd take the opportunity and ask for feedback from real world problem :)

**Comment by pierreozoux** [comment] 2018-03-11 10:35
Mentionned this issue in this new project, I'd love your feedback:
https://github.com/libresh/catalog

**Comment by hex-m** [comment] 2020-12-08 14:52
possible duplicates:
- https://github.com/vector-im/element-web/issues/6827
- https://github.com/vector-im/vector.im/issues/73

related:
- https://github.com/matrix-org/synapse/issues/2693
- https://github.com/matrix-org/synapse/issues/1199
- https://github.com/matrix-org/matrix-doc/pull/2301
- https://github.com/vector-im/element-android/issues/157

Other projects that have a "recommended Servers" list are [Peertube](https://joinpeertube.org/instances#instances-list) and [Mastodon](https://joinmastodon.org/communities).

The more technical approach would be a public service that checks server configurations. This may also motivate admins to harden their config. Examples would be the [IM Observatory](https://xmpp.net/) and [Nextcloud Security Scan](https://scan.nextcloud.com/).

Except for the mentioned [hello-matrix](https://www.hello-matrix.net/public_servers.php) we currently also have a nice list at https://publiclist.anchel.nl/ and it seems like @ara4n started a [list](https://github.com/ara4n/matrixservers) years ago.

**Comment by MTRNord** [comment] 2021-01-13 23:12
Also throwing my WIP https://github.com/keymaker-mx/keymaker into the mix. Still not fully ready but it is moving quickly. It replicates the mastodon version. (See https://joinmatrix.rocks or https://homeservers.mx )

**Comment by thibaultamartin** [comment] 2023-06-22 08:08
Information in hello-matrix seems rather outdated. I'm closing this issue in favour of #1570

**Closed by thibaultamartin** 2023-06-22 08:08 UTC
Labels: enhancement
