### ISSUE TITLE
Improve permalinks for eg code of conduct

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#297] opened 2018-12-13 11:49 UTC
jekyll config is /docs/:category/:title, ideally this would be simplified but I did not succeed at changing the current jekyll config.

**Comment by turt2live** [comment] 2018-12-13 16:46
Duplicate of https://github.com/matrix-org/matrix.org/issues/288 ?

**Closed** 2018-12-13 16:52 UTC
